### ISSUE TITLE
Actualización RoadMap

### ISSUE THREAD

**Issue by milo19980525** [udistrital/cumplidos_dve_cliente#100]
Teniendo en cuenta los líneamientos establecidos para la contratación 2023 de la oficina apoyar técnicamente en la creación del [roadmap](https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7Bc8b13929-fc88-4ea1-b494-60b97b651bf8%7D&action=default&cid=667f4e85-63ba-4622-bdf7-15f1837bcd84) para Cumplidos DVE.

**Especificaciones técnicas**

- Establecer las actividades y subactividades del roamap relacionadas con los features actuales y en prospectiva.
- Tener en cuenta una estimación inicial en puntos de historia.
- Agrupar las actividades y subactividades en milestones o sprints teniendo en cuenta la disponibilidad del equipo.

**Sub Tareas**

- [x] Realizar la definición de actividades y subactividades asociadas a los hitos 2, 3, 4 y 5
- [x] Establecer en SP la estimación de las actividades y sibactividades definidas.
- [x] Agrupar actividades y subactividades en milestones teniendo en cuenta la capacidad del equipo asumiendo dos desarrolladores tiempo completo y uno parcial.

**Criterios de aceptación**

- [x] Comentario en issue que proporcione un resumen de las actividades agregadas al roadmap diariamente.
- [x] Actualización de actividades en el roadmap.

**Requerimientos**

- [x] Especificación de requerimientos (En dado caso de no tenerlos refinados aún colocar estimación inical)

**Dependencias**

- Ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

**Comment by a52290451** [comment]
Se realiza actualización del RoadMap agregando los siguientes Hitos:

Hito 2: Módulo de notificaciones.
Hito 3: Mejoras del sistema.

En cada uno se listaron los items de trabajo requeridos, segun su análisis previo.

Con esto se completa parcialmente el RoadMap de Cumplidos DVE, quedando pendiente Refinar el feature "Replicación de información" con mas items de trabajo relacionados.

Link RoadMap: [https://udistritaleduco-my.sharepoint.com/❌/g/personal/computo_udistrital_edu_co/ESk5sciI_KFOtJRguXtlG_gBt6kwfjF5NuXpY8JJgmX4_w?e=a7ofA7](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ESk5sciI_KFOtJRguXtlG_gBt6kwfjF5NuXpY8JJgmX4_w?e=a7ofA7)](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ESk5sciI_KFOtJRguXtlG_gBt6kwfjF5NuXpY8JJgmX4_w?e=ZJ7PFC)

**Comment by a52290451** [comment]
Se realiza la creación de los issues #106 y #105
